# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  java_build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "gradle.properties" }}
      - restore_cache:
          keys:
          - v2-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - run: ./gradlew resolveDependencies
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v2-dependencies-{{ checksum "gradle.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v2-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - run: ./gradlew build
  java_sonarqube:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "gradle.properties" }}
      - restore_cache:
          keys:
          - v2-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - run: ./gradlew resolveDependencies
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v2-dependencies-{{ checksum "gradle.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v2-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - run: ./gradlew sonarqube -Dsonar.organization=budgetfreak-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_LOGIN}
workflows:
  version: 2
  build:
    jobs:
      - java_build
      - java_sonarqube
        requires:
          - java_build
        filters:
          branches:
            only: master