version: 2
jobs:
  java_build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          key: v2-dependencies-{{ checksum "gradle.properties" }}
      - restore_cache:
          key: v2-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - run: ./gradlew resolveDependencies
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v2-dependencies-{{ checksum "gradle.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v2-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - run: ./gradlew build
      - persist_to_workspace:
          root: ~/repo
          paths: *
  java_sonarqube:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run:
          name: Set PR number (fix for missing envorinment variable)
          command: |
              echo "CIRCLE_PR_NUMBER: $CIRCLE_PR_NUMBER"
              echo "CIRCLE_PULL_REQUEST: $CIRCLE_PULL_REQUEST"
              echo 'export CIRCLE_PR_NUMBER="${CIRCLE_PR_NUMBER:-${CIRCLE_PULL_REQUEST##*/}}"' >> $BASH_ENV
              source $BASH_ENV
              echo "CIRCLE_PR_NUMBER: $CIRCLE_PR_NUMBER"
      - attach_workspace:
          at: ~/repo
      - run: ./gradlew sonarqube
  java_sonarqube_update_pr:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run:
          name: Set PR number (fix for missing envorinment variable)
          command: |
              echo "CIRCLE_PR_NUMBER: $CIRCLE_PR_NUMBER"
              echo "CIRCLE_PULL_REQUEST: $CIRCLE_PULL_REQUEST"
              echo 'export CIRCLE_PR_NUMBER="${CIRCLE_PR_NUMBER:-${CIRCLE_PULL_REQUEST##*/}}"' >> $BASH_ENV
              source $BASH_ENV
              echo "CIRCLE_PR_NUMBER: $CIRCLE_PR_NUMBER"
      - attach_workspace:
          at: ~/repo
      - run: ./gradlew sonarqube -PsonarAnalyzePR
  angular_check:
      working_directory: ~/repo
      docker:
        - image: circleci/node:6-browsers
      steps:
        - checkout
        - restore_cache:
            key: v3-node-dependencies-{{ checksum "web/package.json" }}-{{ checksum "web/package-lock.json" }}
        - run:
            command: npm install
            working_directory: ~/repo/web
        - save_cache:
            key: v3-node-dependencies-{{ checksum "web/package.json" }}-{{ checksum "web/package-lock.json" }}
            paths: web/node_modules
        - run:
            command: xvfb-run -a npm run test -- --single-run --no-progress --browser=ChromeNoSandbox
            working_directory: ~/repo/web
        - run:
            command: xvfb-run -a npm run e2e -- --no-progress --config=protractor-ci.conf.js
            working_directory: ~/repo/web
workflows:
  version: 2
  build_and_analze:
    jobs:
      - java_build
      - java_sonarqube:
          requires:
            - java_build
      - java_sonarqube_update_pr:
          requires:
            - java_build
          filters:
            branches:
              ignore: master
      - angular_check