CREATE TABLE BF_CATEGORY (
  ID IDENTITY,
  NAME VARCHAR(300) NOT NULL,
  DESCRIPTION VARCHAR(300),
  MASTERCATEGORY_ID BIGINT,
  USER_ID BIGINT NOT NULL,
  TYPE VARCHAR(300) NOT NULL,

  CONSTRAINT PK_CATEGORY PRIMARY KEY(ID),
  CONSTRAINT FK_CATEGORY_MASTERCATEGORY FOREIGN KEY(MASTERCATEGORY_ID) REFERENCES BF_MASTERCATEGORY(ID),
  CONSTRAINT FK_CATEGORY_USER FOREIGN KEY(USER_ID) REFERENCES BF_USER(ID),
  CONSTRAINT CK_MASTER_CATEGORY CHECK ((TYPE = 'USER_DEFINED' AND MASTERCATEGORY_ID IS NOT NULL) OR (TYPE <> 'USER_DEFINED' AND MASTERCATEGORY_ID IS NULL))
)