CREATE TABLE BF_BUDGET (
  ID IDENTITY,
  YEAR INT NOT NULL,
  MONTH INT NOT NULL,
  USER_ID BIGINT NOT NULL,

  CONSTRAINT PK_BUDGET PRIMARY KEY(ID),
  CONSTRAINT FK_BUDGET_USER FOREIGN KEY(USER_ID) REFERENCES BF_USER(ID)
)