CREATE TABLE BF_CATEGORY (
  ID IDENTITY,
  NAME VARCHAR(300) NOT NULL,
  DESCRIPTION VARCHAR(300),
  MASTERCATEGORY_ID BIGINT NOT NULL,

  CONSTRAINT PK_CATEGORY PRIMARY KEY(ID),
  CONSTRAINT FK_CATEGORY_MASTERCATEGORY FOREIGN KEY(MASTERCATEGORY_ID) REFERENCES BF_MASTERCATEGORY(ID)
)