CREATE TABLE BF_TRANSACTION (
  ID IDENTITY,
  AMOUNT DECIMAL(20,2) NOT NULL,
  BOOKING_DATE TIMESTAMP NOT NULL,
  DESCRIPTION VARCHAR(300),
  CLEARED BOOLEAN NOT NULL,
  PAYEE_ID BIGINT NOT NULL,
  CATEGORY_ID BIGINT NOT NULL,
  ACCOUNT_ID BIGINT NOT NULL,

  CONSTRAINT PK_TRANSACTION PRIMARY KEY(ID),
  CONSTRAINT FK_TRANSACTION_PAYEE FOREIGN KEY(PAYEE_ID) REFERENCES BF_PAYEE(ID),
  CONSTRAINT FK_TRANSACTION_CATEGORY FOREIGN KEY(CATEGORY_ID) REFERENCES BF_CATEGORY(ID),
  CONSTRAINT FK_TRANSACTION_ACCOUNT FOREIGN KEY(ACCOUNT_ID) REFERENCES BF_ACCOUNT(ID)
)