INSERT INTO BF_USER (NAME, CURRENCY) VALUES
  ('Max', '€');
SELECT @max := SCOPE_IDENTITY();

INSERT INTO BF_USER (NAME, CURRENCY) VALUES
  ('Maria', '$');
SELECT @maria := SCOPE_IDENTITY();


INSERT INTO BF_ACCOUNT (DESCRIPTION, ON_BUDGET, USER_ID)
 VALUES ('Giro', true, @max);
INSERT INTO BF_ACCOUNT (DESCRIPTION, ON_BUDGET, USER_ID)
 VALUES ('Bargeld', true, @max);
INSERT INTO BF_ACCOUNT (DESCRIPTION, ON_BUDGET, USER_ID)
VALUES ('Sparbuch', true, @maria);